app:
  version: 0.0.1-SNAPSHOT

server:
  servlet:
    context-path: '/api'
  port: 8080

url:
  beneficiario: 'https://aposentadoria-beneficiario-api.herokuapp.com'
  caixa-eletronico: 'https://aposentadoria-caixa-api.herokuapp.com'

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "https://aposentadoria-app.herokuapp.com"
            allowedHeaders:
              - content-type
              - x-requested-with
              - Authorization
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - DELETE
              - PUT
